### ISSUE TITLE
Sometimes trouble saving database

### ISSUE THREAD

**Issue by turesheim** [turesheim/eclipse-timekeeper#107]
```
javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.4.v20160829-44060b6): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.SocketTimeoutException: connect timed out: 169.254.67.122:9090" [90067-192]
Error Code: 90067
...
Caused by: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.SocketTimeoutException: connect timed out: 169.254.67.122:9090" [90067-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:452)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:362)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
	at org.h2.Driver.connect(Driver.java:72)
	at org.eclipse.persistence.sessions.DefaultConnector.directConnect(DefaultConnector.java:165)
	... 60 more
```

**Comment by turesheim** [comment]
The H2 server should be using 127.0.0.1 instead of the LAN address. Moving to new network will break the connection.

**Comment by turesheim** [comment]
Solution is here: http://h2database.com/html/advanced.html?highlight=bind,address&search=bind%20address#server_bind_address
