### ISSUE TITLE
error log shows lot of "java.lang.NullPointerException" from net.resheim.eclipse.timekeeper.internal.idle.WindowsIdleTimeDetector

### ISSUE THREAD

**Issue by anb0s** [turesheim/eclipse-timekeeper#60]
Eclipse IDE for C/C++ Developers (x64)
  Version: Luna Service Release 1a (4.4.1)
  Build id: 20150109-0600

Windows 8.1 x64

Exception:
java.lang.NullPointerException
	at com.sun.jna.Structure.getFields(Structure.java:911)
	at com.sun.jna.Structure.deriveLayout(Structure.java:1058)
	at com.sun.jna.Structure.calculateSize(Structure.java:982)
	at com.sun.jna.Structure.calculateSize(Structure.java:949)
	at com.sun.jna.Structure.allocateMemory(Structure.java:375)
	at com.sun.jna.Structure.<init>(Structure.java:184)
	at com.sun.jna.Structure.<init>(Structure.java:172)
	at com.sun.jna.Structure.<init>(Structure.java:159)
	at com.sun.jna.Structure.<init>(Structure.java:151)
	at net.resheim.eclipse.timekeeper.internal.idle.WindowsIdleTimeDetector$LastInputInfo.<init>(WindowsIdleTimeDetector.java:36)
	at net.resheim.eclipse.timekeeper.internal.idle.WindowsIdleTimeDetector.getIdleTimeMillis(WindowsIdleTimeDetector.java:95)
	at net.resheim.eclipse.timekeeper.ui.Activator$2.handleEvent(Activator.java:556)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1262)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

**Comment by anb0s** [comment]
The exceptions are shown very often after Work Week view was opened. The it is not possible to close editor or views inside Eclipse with [X]. Only right click "Close" is working. After Eclipse restart closind is working again until Work Week view is opened.

**Comment by turesheim** [comment]
Thanks for the report - appears to be a problem with the idle-detector on Windows. I'll have a look.

**Comment by turesheim** [comment]
Tested OK on Windows 7 - please verify once I get the 1.0.1 build out.

**Comment by turesheim** [comment]
I have a temporary 1.0.1 build at http://resheim.net/p2/eclipse-timekeeper_1.0.1.

**Comment by anb0s** [comment]
I've used the version 1.0.1 and do not see any exceptions. Thank You for the quick fix :)
