### ISSUE TITLE
Error logged filled with unhandled event loop exceptions: java.lang.NullPointerException

### ISSUE THREAD

**Issue by rombert** [turesheim/eclipse-timekeeper#61]
Running

eclipse.buildId=4.4.1.M20140925-0400
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

The full stack trace is

```
java.lang.NullPointerException
	at com.sun.jna.Structure.getFields(Structure.java:911)
	at com.sun.jna.Structure.deriveLayout(Structure.java:1058)
	at com.sun.jna.Structure.calculateSize(Structure.java:982)
	at com.sun.jna.Structure.calculateSize(Structure.java:949)
	at com.sun.jna.Structure.allocateMemory(Structure.java:375)
	at com.sun.jna.Structure.<init>(Structure.java:184)
	at com.sun.jna.Structure.<init>(Structure.java:172)
	at com.sun.jna.Structure.<init>(Structure.java:159)
	at com.sun.jna.Structure.<init>(Structure.java:151)
	at net.resheim.eclipse.timekeeper.internal.idle.X11IdleTimeDetector$XScreenSaverInfo.<init>(X11IdleTimeDetector.java:44)
	at net.resheim.eclipse.timekeeper.internal.idle.X11IdleTimeDetector.getIdleTimeMillis(X11IdleTimeDetector.java:130)
	at net.resheim.eclipse.timekeeper.ui.Activator$2.handleEvent(Activator.java:556)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1574)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1387)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3799)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3409)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
	at org.eclipse.jface.window.Window.open(Window.java:808)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:341)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:371)
	at org.eclipse.jface.dialogs.MessageDialog.openQuestion(MessageDialog.java:466)
	at org.eclipse.equinox.p2.ui.RevertProfilePage$4.run(RevertProfilePage.java:267)
	at org.eclipse.equinox.p2.ui.RevertProfilePage.buttonPressed(RevertProfilePage.java:288)
	at org.eclipse.equinox.internal.p2.ui.sdk.RevertProfilePageWithCompare.buttonPressed(RevertProfilePageWithCompare.java:67)
	at org.eclipse.ui.about.InstallationPage$1.widgetSelected(InstallationPage.java:136)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4454)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1388)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3799)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3409)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
	at org.eclipse.jface.window.Window.open(Window.java:808)
	at org.eclipse.ui.internal.dialogs.AboutDialog$1.run(AboutDialog.java:129)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.dialogs.AboutDialog.buttonPressed(AboutDialog.java:123)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4454)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1388)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3799)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3409)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
	at org.eclipse.jface.window.Window.open(Window.java:808)
	at org.eclipse.ui.internal.about.AboutHandler.execute(AboutHandler.java:33)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:247)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:229)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:149)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:343)
	at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:159)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4454)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1388)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3799)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3409)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by turesheim** [comment]
Thanks I'll have a look. What Linux flavor are you on?

**Comment by rombert** [comment]
openSuSE 13.2 x86_64

Thanks

**Comment by turesheim** [comment]
I've not been able to test this on openSuSE yet, but I believe I have a fix. Could you please try the temporary 1.0.1 release at http://resheim.net/p2/eclipse-timekeeper_1.0.1.

**Comment by rombert** [comment]
@turesheim - thanks for the fix. However, I'm not able to use the provided update site; I get

> java.io.IOException: http://resheim.net/p2/eclipse-timekeeper_1.0.1/ is not a valid repository location.

**Comment by turesheim** [comment]
Hi Robert,

Make sure you use HTTPS, not HTTP. The p2 client does not follow redirects.

**Comment by rombert** [comment]
HTTPS works, thank you. And the fix looks good to me as well.

On Mon, Feb 23, 2015 at 5:00 PM, Torkild U. Resheim <
notifications@github.com> wrote:

> Hi Robert,
>
> Make sure you use HTTPS, not HTTP. The p2 client does not follow redirects.
>
> > 23. feb. 2015 kl. 15.50 skrev Robert Munteanu <notifications@github.com
> >:
> >
> > @turesheim - thanks for the fix. However, I'm not able to use the
> provided update site; I get
> >
> > java.io.IOException: http://resheim.net/p2/eclipse-timekeeper_1.0.1/ is
> not a valid repository location.
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/turesheim/eclipse-timekeeper/issues/61#issuecomment-75556616>
> .
>



-- 
http://robert.muntea.nu/
